version: "3.6"

services: 
  # Node Backed API
  node:
    build: 
      context: .
      dockerfile: node.dockerfile
    command: npm start 
    working_dir: /var/www
    environment:
      POSTGRES_URI: postgres://postgres:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    networks:
      - backend-network
    ports:
      - 3000:3000
    volumes:
     - .:/var/www
  # Postgres service
  postgres:
    build: ./initdb

    # Expose the default Postgres port on localhost
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'smart-brain-docker'
    networks:
      - backend-network
  
  # Redis service
  redis:
    image: redis
    ports:
      - '6379:6379' 
    networks: 
      - backend-network
networks: 
  backend-network:
    driver: bridge
   